### ISSUE TITLE
Error: RGB Terrain rendering in MapLibreGL base shifted vertically -10000

### ISSUE THREAD

**Issue by Fakhriyramadhan25** [watergis/terrain-rgb#18]
Hi there,

I am developing a 3D terrain using Maplibre GL, i want to use my own DEM data to visualize the terrain. I have converted DEM with EPSG:3857 into RGB terrain by utilizing [water-gis](https://water-gis.com/en/setups/terrain-rgb/create_terrainrgb/) tools. The tools comply with the MaplibreGL equation: height = -10000 + ((R * 256 * 256 + G * 256 + B) * 0.1).
Nonetheless, when i tried to visualize the raster-tiles into the raster-dem there is a vertical distortion occurred, it is shifted vertically, the picture as follows: 
![base-10000](https://github.com/watergis/terrain-rgb/assets/49341041/7d7562d2-5f1d-4a09-87cf-691b65307924)

To debug this error, i have tried to change the base of the equation from (-10000) to (0) but it turns out that evoke other error to the terrain. The zoom level can only enable until 12, after that the map returns blank white screen. The base still shifted vertically but not as significant when the base is (-10000), picture as follows: 
![base-0](https://github.com/watergis/terrain-rgb/assets/49341041/d97eb11a-34dd-4a35-9ee6-018f863a1930)

Other debugging effort is by customizing the encoding of maplibre, the code as follows: 
```
 // Use a different source for terrain and hillshade layers, to improve render quality
              terrainSource: {
                type: 'raster-dem',
                // url: 'https://demotiles.maplibre.org/terrain-tiles/tiles.json',
                tiles: ['http://localhost:5173/BDGtiles/{z}/{x}/{y}.png'],
                tileSize: 256,
                encoding: "custom",
                baseShift: 10000,
                redFactor: 0,
                greenFactor:1,
                blueFactor:1
}
```

The terrain touches the ground with this method but the terrain surface getting rougher and abstract. image as follows: 
![baseshift-0](https://github.com/watergis/terrain-rgb/assets/49341041/990be1fa-abe5-4ea2-a08a-dae8edac5dd9)

How can i repair the base shifting issue from -10000 to 0 without causing any other bug?

Thank You

**Comment by JinIgarashi** [comment]
@Fakhriyramadhan25 Thanks for using watergis's terrain-rgb documentation (It has been written long time ago, and I have not updated it at all, I am not sure whether it works properly now)

I think the behaviour of maplibre with your Mapbox terrain-rgb is normal. 

The formula of `elevation = -10000 + ((R * 256 * 256 + G * 256 + B) * 0.1)` is fixed. See the below maptiler blog. 
https://documentation.maptiler.com/hc/en-us/articles/4405444055313-RGB-Terrain-by-MapTiler

In my opinition, this issue is not a problem of terrain-rgb, it is a problem of your raster-dem data's coverage is limited.

See the below website which is one of water utilities of Kenya uses water-gis tools (please enable terrain). 

https://new.nawascogis.co.ke/?style=UN+Vector+Tile#7.99/-0.502/36.857/8.8/72

![image](https://github.com/watergis/terrain-rgb/assets/2639701/5c20b115-2518-4cfd-8797-2239037b88ed)

The area's altitude is mostly above 2000m if the raster-dem tileset in the area is only the one enabled terrain in maplibre. This cause looks very different from base map when users zoom out. But in this utility's case, I think this visualisation does not matter (depending on your customer).

I have nerver used `baseShift` of maplibre, maybe it works. I think `ecoding: cutom` is generaly for customised raster-dem source other than using terrain-rgb and terrarium.

Maybe it is worth asking about this issue in Maplibre's slack channel. Someone might have a solution.
